# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
